/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.BDatos;
import Modelo.BDatosDao;
import Modelo.UsuarioLogin;
import com.placeholder.PlaceHolder;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import javax.swing.ImageIcon;

/**
 *
 * @author Jhonas
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
   

    
    public Login() {
        initComponents();
        
        PlaceHolder holderUsuario = new PlaceHolder(CampoUsuario, "Usuario");
        PlaceHolder holderClave = new PlaceHolder(CampoClave, "Contraseña");
        setLocationRelativeTo(null);
        URL url = getClass().getResource("/Vista/Iconos UI/logoFrame.png");
        ImageIcon img = new ImageIcon(url);
        setIconImage(img.getImage());
        /*Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Vista/Iconos UI/logoFrame.png"));
        setIconImage(icon);
        setVisible(true);*/
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogin = new javax.swing.JPanel();
        CampoUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CampoClave = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLogin.setBackground(new java.awt.Color(255, 255, 255));
        PanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CampoUsuario.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        CampoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        CampoUsuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CampoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoUsuarioActionPerformed(evt);
            }
        });
        PanelLogin.add(CampoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 320, 30));

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel1.setText("Contraseña:");
        PanelLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel2.setText("Nombre de Usuario:");
        PanelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("LOGIN");
        PanelLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 50));
        PanelLogin.add(CampoClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 320, 30));

        btnIngresar.setBackground(new java.awt.Color(46, 204, 113));
        btnIngresar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        PanelLogin.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 210, 50));

        btnSalir.setBackground(new java.awt.Color(231, 76, 60));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        PanelLogin.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 210, -1));

        jSeparator1.setBackground(new java.awt.Color(22, 160, 133));
        jSeparator1.setForeground(new java.awt.Color(22, 160, 133));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 450, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/LoginIcon/clave.png"))); // NOI18N
        PanelLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/LoginIcon/usuario.png"))); // NOI18N
        PanelLogin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jPanel1.setBackground(new java.awt.Color(22, 160, 133));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelLogin.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 470, 110));

        getContentPane().add(PanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        String usuario = CampoUsuario.getText();
        String clave = CampoClave.getText();
        new Menu().getUsuarioActual().setText(usuario);
        new MenuInvitado().getUsuarioActual().setText(usuario);
        Date fecha = new Date();
        SimpleDateFormat form = new SimpleDateFormat("dd/MM/yyyy");
        String fech = form.format(fecha);
        new Menu().getFechaActual().setText(fech);
        new MenuInvitado().getFechaActual().setText(fech);
        Calendar calendario = new GregorianCalendar();
        int hora = calendario.get(Calendar.HOUR);
        int minuto = calendario.get(Calendar.MINUTE);
        int segundo = calendario.get(Calendar.SECOND);
        
        //String horas = String.valueOf(hora+":"+minuto+":"+segundo);
        
       // new Menu().getHoraActual().setText(horas);
        
        UsuarioLogin user = new UsuarioLogin(usuario, clave);
        new BDatosDao().sesion(user, this);
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
       
       
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CampoClave;
    private javax.swing.JTextField CampoUsuario;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
