/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.BDatos;
import Modelo.CrudDao.CategoriaDao;
import Modelo.CrudDao.ClienteDao;
import Modelo.CrudDao.ProductoDao;
import Modelo.CrudDao.ProveedorDao;
import Modelo.Mantenimiento.Categoria;
import Modelo.Mantenimiento.Cliente;
import Modelo.Mantenimiento.Producto;
import Modelo.Mantenimiento.Proveedor;
import Modelo.MantenimientoDao;
import Modelo.Usuario;
import Vista.CRUB.EditarUsuario;
import com.placeholder.PlaceHolder;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhonas
 */
public class Mantenimiento extends javax.swing.JFrame {

    /**
     * Creates new form Mantenimiento
     */
    MantenimientoDao mant = new MantenimientoDao();
    ArrayList<Usuario> u = mant.listarUsuarios();
     java.util.Date cast;
    public Mantenimiento() {
        initComponents();
        //PlaceHolder holderUsuario = new PlaceHolder(CodigoUsuario, "CODIGO (autogenerado)");
        PlaceHolder holderNick = new PlaceHolder(NickName, "NOMBRE DE USUARIO");
        PlaceHolder holderNombre = new PlaceHolder(UsuarioNombre, "NOMBRE");
        PlaceHolder holderApellido = new PlaceHolder(UsuarioApellido, "APELLIDO");
        PlaceHolder holderClave = new PlaceHolder(UsuarioClave, "CLAVE");
        
        ArrayList<Producto> u = new ProductoDao().listarProducto();
        new ProductoDao().listarTabla(tblProducto, u);
        
        btnActualizarUsuario.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnActualizarProducto.setEnabled(false);
        btnCancelarProducto.setEnabled(false);
        comboProveedor.removeAllItems();
        UsuarioNombre.setOpaque(false);
        ArrayList<String> listaComboProveedor = new ArrayList<String>();
        listaComboProveedor = new ProductoDao().comboProveedor();
        for(int i = 0; i < listaComboProveedor.size(); i++)
        {
            comboProveedor.addItem(listaComboProveedor.get(i));
        }
        setLocationRelativeTo(null);
        URL url = getClass().getResource("/Vista/Iconos UI/logoFrame.png");
        ImageIcon img = new ImageIcon(url);
        setIconImage(img.getImage());
        comboCategoria.removeAllItems();
        ArrayList<String> listaComboCategoria = new ArrayList<String>();
        listaComboCategoria = new ProductoDao().comboCategoria();
        for(int i = 0; i < listaComboCategoria.size(); i++)
        {
            comboCategoria.addItem(listaComboCategoria.get(i));
        }   
        
       /*Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Vista/Iconos UI/logoFrame.png"));
        setIconImage(icon);
        setVisible(true);*/
        //PlaceHolder holderClave = new PlaceHolder(CampoClave, "Contraseña");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PestanasMantenimiento = new javax.swing.JTabbedPane();
        PanelUsuarios = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        ScrollUsuarios = new javax.swing.JScrollPane();
        usuarios = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        Nivel = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        UsuarioClave = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        NickName = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        UsuarioApellido = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        UsuarioNombre = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        limpiarUsuario = new javax.swing.JButton();
        btnActualizarUsuario = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        PanelProducto = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        ScrollUsuarios3 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        txtProducto = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        btnEditarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnListarProducto = new javax.swing.JButton();
        txtPrecioCompraOff = new javax.swing.JTextField();
        txtPrecioVentaOff = new javax.swing.JTextField();
        txtCantidadOff = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        comboProveedor = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fechaProducto = new com.toedter.calendar.JDateChooser();
        btnAgregarProducto = new javax.swing.JButton();
        limpiarProducto = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        btnActualizarProducto = new javax.swing.JButton();
        btnCancelarProducto = new javax.swing.JButton();
        txtCantidad = new javax.swing.JSpinner();
        txtPrecioCompra = new javax.swing.JSpinner();
        txtPrecioVenta = new javax.swing.JSpinner();
        PanelCliente = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        ScrollUsuarios4 = new javax.swing.JScrollPane();
        tblCategoria = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        btnEditarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        btnListarCliente = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        btnAgregarCliente = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        limpiarCategoria = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        Proveedores = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        ScrollUsuarios5 = new javax.swing.JScrollPane();
        tblProveedor = new javax.swing.JTable();
        txtNombreProveedor = new javax.swing.JTextField();
        txtTelefonoProveedor = new javax.swing.JTextField();
        txtEmailProveedor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnAgregarProveedor = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        btnEditaProveedor = new javax.swing.JButton();
        btnEliminarProveedor = new javax.swing.JButton();
        btnListarProveedor = new javax.swing.JButton();
        txtDireccionProveedor = new javax.swing.JTextField();
        limpiarProveedor = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mantenimiento");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PestanasMantenimiento.setBackground(new java.awt.Color(255, 255, 255));
        PestanasMantenimiento.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        PanelUsuarios.setBackground(new java.awt.Color(22, 160, 133));
        PanelUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScrollUsuarios.setBackground(new java.awt.Color(255, 255, 255));

        usuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        usuarios.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "APELLIDO", "NOMBRE DE USUARIO", "CLAVE", "NIVEL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usuarios.setGridColor(new java.awt.Color(255, 255, 255));
        usuarios.setIntercellSpacing(new java.awt.Dimension(5, 5));
        ScrollUsuarios.setViewportView(usuarios);

        jPanel4.add(ScrollUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 990, 250));

        jPanel8.setBackground(new java.awt.Color(22, 160, 133));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 153, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/delete-user.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel8.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, 40));

        btnListar.setBackground(new java.awt.Color(255, 255, 255));
        btnListar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnListar.setForeground(new java.awt.Color(0, 153, 0));
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/list-user.png"))); // NOI18N
        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jPanel8.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 150, 40));

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(0, 153, 0));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/edit-user.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel8.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 40));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 540));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 153, 0));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/salida.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel4.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 153, 0));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/boton-crear-grupo.png"))); // NOI18N
        btnAdd.setText("GUARDAR");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        Nivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2"}));
        Nivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NivelActionPerformed(evt);
            }
        });
        jPanel1.add(Nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 260, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Rol de Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));
        jPanel1.add(UsuarioClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 430, 30));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Contraseña:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, 20));
        jPanel1.add(NickName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 430, 30));

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel20.setText("Usuario:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        jPanel1.add(UsuarioApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 430, 30));

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel21.setText("Apellido:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
        jPanel1.add(UsuarioNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 430, 30));

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setText("Nombre:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel22.setText("AGREGAR NUEVO USUARIO");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        limpiarUsuario.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        limpiarUsuario.setText("Limpiar Campos");
        limpiarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(limpiarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 150, 20));

        btnActualizarUsuario.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnActualizarUsuario.setText("ACTUALIZAR");
        btnActualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 140, 40));

        btnCancelar.setText("Cancelar Actualización");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 150, 20));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 800, 360));

        PanelUsuarios.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 540));

        PestanasMantenimiento.addTab("USUARIOS", PanelUsuarios);

        PanelProducto.setBackground(new java.awt.Color(39, 174, 96));
        PanelProducto.setLayout(new javax.swing.BoxLayout(PanelProducto, javax.swing.BoxLayout.LINE_AXIS));

        jPanel9.setBackground(new java.awt.Color(22, 160, 133));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelProducto.add(jPanel9);

        jPanel6.setBackground(new java.awt.Color(22, 160, 133));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScrollUsuarios3.setBackground(new java.awt.Color(255, 255, 255));

        tblProducto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblProducto.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOMBRE", "DESCRIPCIÓN", "CATEGORÍA", "PROVEEDOR", "PRECIO DE COMPRA", "PRECIO DE VENTA", "FECHA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProducto.setGridColor(new java.awt.Color(255, 255, 255));
        tblProducto.setIntercellSpacing(new java.awt.Dimension(5, 5));
        ScrollUsuarios3.setViewportView(tblProducto);

        jPanel7.add(ScrollUsuarios3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 990, 190));
        jPanel7.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 230, 30));

        jPanel12.setBackground(new java.awt.Color(22, 160, 133));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditarProducto.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarProducto.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEditarProducto.setForeground(new java.awt.Color(0, 153, 0));
        btnEditarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/edit-user.png"))); // NOI18N
        btnEditarProducto.setText("EDITAR");
        btnEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProductoActionPerformed(evt);
            }
        });
        jPanel12.add(btnEditarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 40));

        btnEliminarProducto.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarProducto.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEliminarProducto.setForeground(new java.awt.Color(0, 153, 0));
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/delete-user.png"))); // NOI18N
        btnEliminarProducto.setText("ELIMINAR");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });
        jPanel12.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, 40));

        btnListarProducto.setBackground(new java.awt.Color(255, 255, 255));
        btnListarProducto.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnListarProducto.setForeground(new java.awt.Color(0, 153, 0));
        btnListarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/list-user.png"))); // NOI18N
        btnListarProducto.setText("LISTAR");
        btnListarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProductoActionPerformed(evt);
            }
        });
        jPanel12.add(btnListarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 150, 40));
        jPanel12.add(txtPrecioCompraOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 200, 30));
        jPanel12.add(txtPrecioVentaOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 200, 30));
        jPanel12.add(txtCantidadOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 200, 30));

        jPanel7.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 580));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Nombre de Producto:");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel23.setText("AGREGAR NUEVO PRODUCTO");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Descripcion:");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));
        jPanel7.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 320, 30));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Categoría:");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2"}));
        comboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriaActionPerformed(evt);
            }
        });
        jPanel7.add(comboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 230, 30));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setText("Proveedor:");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, -1, -1));

        comboProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2"}));
        comboProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProveedorActionPerformed(evt);
            }
        });
        jPanel7.add(comboProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 350, 30));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Cantidad:");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Precio de compra:");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 160, 20));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setText("Precio de venta:");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 160, 20));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setText("Fecha:");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 90, 20));
        jPanel7.add(fechaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 240, 30));

        btnAgregarProducto.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAgregarProducto.setForeground(new java.awt.Color(0, 153, 0));
        btnAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/boton-crear-grupo.png"))); // NOI18N
        btnAgregarProducto.setText("GUARDAR");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        jPanel7.add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 150, 40));

        btnSalirProducto.setBackground(new java.awt.Color(255, 255, 255));
        btnSalirProducto.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSalirProducto.setForeground(new java.awt.Color(0, 153, 0));
        btnSalirProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/salida.png"))); // NOI18N
        btnSalirProducto.setText("SALIR");
        btnSalirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirProductoActionPerformed(evt);
            }
        });
        jPanel7.add(btnSalirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, -1, -1));

        limpiarProducto.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        limpiarProducto.setText("Limpiar Campos");
        limpiarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarProductoActionPerformed(evt);
            }
        });
        jPanel7.add(limpiarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 150, 20));

        btnEditar1.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEditar1.setForeground(new java.awt.Color(0, 153, 0));
        btnEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/edit-user.png"))); // NOI18N
        btnEditar1.setText("EDITAR");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });
        jPanel7.add(btnEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 40));

        btnActualizarProducto.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnActualizarProducto.setText("ACTUALIZAR");
        btnActualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarProductoActionPerformed(evt);
            }
        });
        jPanel7.add(btnActualizarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 140, 40));

        btnCancelarProducto.setText("Cancelar Actualización");
        btnCancelarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProductoActionPerformed(evt);
            }
        });
        jPanel7.add(btnCancelarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 150, 20));
        jPanel7.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 70, 30));
        jPanel7.add(txtPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 140, 30));
        jPanel7.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 120, 30));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 540));

        PanelProducto.add(jPanel6);

        PestanasMantenimiento.addTab("PRODUCTOS", PanelProducto);

        PanelCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(22, 160, 133));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(39, 174, 96));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel16.setBackground(new java.awt.Color(39, 174, 96));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScrollUsuarios4.setBackground(new java.awt.Color(255, 255, 255));

        tblCategoria.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblCategoria.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "#", "NOMBRE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCategoria.setGridColor(new java.awt.Color(255, 255, 255));
        tblCategoria.setIntercellSpacing(new java.awt.Dimension(5, 5));
        ScrollUsuarios4.setViewportView(tblCategoria);

        jPanel17.add(ScrollUsuarios4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 990, 260));

        jPanel18.setBackground(new java.awt.Color(22, 160, 133));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditarCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarCliente.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEditarCliente.setForeground(new java.awt.Color(0, 153, 0));
        btnEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/edit-user.png"))); // NOI18N
        btnEditarCliente.setText("EDITAR");
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });
        jPanel18.add(btnEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 40));

        btnEliminarCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarCliente.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEliminarCliente.setForeground(new java.awt.Color(0, 153, 0));
        btnEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/delete-user.png"))); // NOI18N
        btnEliminarCliente.setText("ELIMINAR");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });
        jPanel18.add(btnEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, 40));

        btnListarCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnListarCliente.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnListarCliente.setForeground(new java.awt.Color(0, 153, 0));
        btnListarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/list-user.png"))); // NOI18N
        btnListarCliente.setText("LISTAR");
        btnListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarClienteActionPerformed(evt);
            }
        });
        jPanel18.add(btnListarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 150, 40));

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 540));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setText("Nombre:");
        jPanel17.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));
        jPanel17.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 370, 30));

        btnAgregarCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarCliente.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAgregarCliente.setForeground(new java.awt.Color(0, 153, 0));
        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/boton-crear-grupo.png"))); // NOI18N
        btnAgregarCliente.setText("AGREGAR");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });
        jPanel17.add(btnAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 150, 40));

        btnSalirCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnSalirCliente.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSalirCliente.setForeground(new java.awt.Color(0, 153, 0));
        btnSalirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/salida.png"))); // NOI18N
        btnSalirCliente.setText("SALIR");
        btnSalirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirClienteActionPerformed(evt);
            }
        });
        jPanel17.add(btnSalirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, -1, -1));

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel24.setText("AGREGAR NUEVA CATEGORIA");
        jPanel17.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        limpiarCategoria.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        limpiarCategoria.setText("Limpiar Campos");
        limpiarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarCategoriaActionPerformed(evt);
            }
        });
        jPanel17.add(limpiarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 540));

        jPanel14.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelCliente.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 650));

        jPanel10.setBackground(new java.awt.Color(22, 160, 133));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(39, 174, 96));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel13.setBackground(new java.awt.Color(39, 174, 96));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel10.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelCliente.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PestanasMantenimiento.addTab("CATEGORIAS", PanelCliente);

        Proveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScrollUsuarios5.setBackground(new java.awt.Color(255, 255, 255));

        tblProveedor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblProveedor.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOMBRE", "TELEFONO", "DIRECCION", "EMAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProveedor.setGridColor(new java.awt.Color(255, 255, 255));
        tblProveedor.setIntercellSpacing(new java.awt.Dimension(5, 5));
        ScrollUsuarios5.setViewportView(tblProveedor);

        jPanel25.add(ScrollUsuarios5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 990, 170));
        jPanel25.add(txtNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 370, 30));
        jPanel25.add(txtTelefonoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 370, 30));
        jPanel25.add(txtEmailProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 370, 30));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setText("Nombre:");
        jPanel25.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setText("Teléfono:");
        jPanel25.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setText("Email:");
        jPanel25.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel19.setText("Dirección:");
        jPanel25.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 80, 20));

        btnAgregarProveedor.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarProveedor.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAgregarProveedor.setForeground(new java.awt.Color(0, 153, 0));
        btnAgregarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/boton-crear-grupo.png"))); // NOI18N
        btnAgregarProveedor.setText("GUARDAR");
        btnAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProveedorActionPerformed(evt);
            }
        });
        jPanel25.add(btnAgregarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 150, 40));

        btnSalirProducto2.setBackground(new java.awt.Color(255, 255, 255));
        btnSalirProducto2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSalirProducto2.setForeground(new java.awt.Color(0, 153, 0));
        btnSalirProducto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/salida.png"))); // NOI18N
        btnSalirProducto2.setText("SALIR");
        btnSalirProducto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirProducto2ActionPerformed(evt);
            }
        });
        jPanel25.add(btnSalirProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, -1, -1));

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel25.setText("AGREGAR NUEVO PROVEEDOR");
        jPanel25.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jPanel26.setBackground(new java.awt.Color(22, 160, 133));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditaProveedor.setBackground(new java.awt.Color(255, 255, 255));
        btnEditaProveedor.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEditaProveedor.setForeground(new java.awt.Color(0, 153, 0));
        btnEditaProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/edit-user.png"))); // NOI18N
        btnEditaProveedor.setText("EDITAR");
        btnEditaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditaProveedorActionPerformed(evt);
            }
        });
        jPanel26.add(btnEditaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 40));

        btnEliminarProveedor.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarProveedor.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEliminarProveedor.setForeground(new java.awt.Color(0, 153, 0));
        btnEliminarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/delete-user.png"))); // NOI18N
        btnEliminarProveedor.setText("ELIMINAR");
        btnEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProveedorActionPerformed(evt);
            }
        });
        jPanel26.add(btnEliminarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, 40));

        btnListarProveedor.setBackground(new java.awt.Color(255, 255, 255));
        btnListarProveedor.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnListarProveedor.setForeground(new java.awt.Color(0, 153, 0));
        btnListarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/list-user.png"))); // NOI18N
        btnListarProveedor.setText("LISTAR");
        btnListarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProveedorActionPerformed(evt);
            }
        });
        jPanel26.add(btnListarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 150, 40));

        jPanel25.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 540));

        txtDireccionProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionProveedorActionPerformed(evt);
            }
        });
        jPanel25.add(txtDireccionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 370, 30));

        limpiarProveedor.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        limpiarProveedor.setText("Limpiar Campos");
        limpiarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarProveedorActionPerformed(evt);
            }
        });
        jPanel25.add(limpiarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, -1, -1));

        Proveedores.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 520));

        jPanel22.setBackground(new java.awt.Color(22, 160, 133));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Proveedores.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1200, 640));

        PestanasMantenimiento.addTab("PROVEEDORES", Proveedores);

        getContentPane().add(PestanasMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 1170, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void NivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NivelActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        
        
        mant.listarTabla(usuarios, u);
       
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
   //public Usuario(int codigo, String nombre, String apellido, String nickName, String clave, int nivel)
        String usuarioNombre = UsuarioNombre.getText();
        String usuarioApellido = UsuarioApellido.getText();
        String nick = NickName.getText();
        String clave = UsuarioClave.getText();
        int nivel = Nivel.getSelectedIndex()+1;
        Usuario us = new Usuario(usuarioNombre, usuarioApellido, nick, clave, nivel);
        mant.agregarUsuario(us);
        
        
        mant.listarTabla(usuarios, u);
        
        

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        new MantenimientoDao().eliminarUsuario(usuarios, btnEliminar);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
       //new EditarUsuario().setVisible(true);
       cargarDatosUsuario();
    }//GEN-LAST:event_btnEditarActionPerformed
   
    public void limpiarUsuarios()
    {
        UsuarioNombre.setText("");
        UsuarioApellido.setText("");
        NickName.setText("");
       UsuarioClave.setText("");
        
    }
    
    public void limpiarProductos()
    {
        txtProducto.setText("");
        txtDescripcion.setText("");
        
        txtCantidadOff.setText("");
        
        txtPrecioVentaOff.setText("");
        txtPrecioCompraOff.setText("");
    }
    
    public void limpiarCategoria()
    {
        txtCategoria.setText("");
    }
    
    public void limpiarProveedores()
    {
        txtNombreProveedor.setText("");
        txtTelefonoProveedor.setText("");
        txtEmailProveedor.setText("");
        txtDireccionProveedor.setText("");
    }
    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        // TODO add your handling code here:
//(String nombre, String descripcion, String categoria, String proveedor, double precio_venta, double precio_compra, int cantidad, Date fecha) {
    String nombre = txtProducto.getText();
    String descripcion = txtDescripcion.getText();
    String categoria = comboCategoria.getSelectedItem().toString();
    String proveedor = comboProveedor.getSelectedItem().toString();
    //String cant 
      int cantidad  = (int)txtCantidad.getValue();
    //int cantidad = Integer.parseInt(cant);
    double precio_venta = (int)txtPrecioVenta.getValue();
    double precio_compra = (int)txtPrecioCompra.getValue();
    java.util.Date cast = fechaProducto.getDate();
    java.sql.Date fecha = new java.sql.Date(cast.getTime());
    
    
    /*SimpleDateFormat form = new SimpleDateFormat("dd-MM-yyyy");
    String fech = form.format(fechaProducto.getDate());
    Date fecha = Date.valueOf(fech);*/
    Producto u = new Producto(nombre, descripcion, categoria, proveedor, precio_venta, precio_compra, cantidad, fecha);
     new ProductoDao().agregarUsuario(u);
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProductoActionPerformed
        // TODO add your handling code here:
        cargarProducto();
    }//GEN-LAST:event_btnEditarProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        // TODO add your handling code here:
        new ProductoDao().eliminarProducto(tblProducto);
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnListarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProductoActionPerformed
        // TODO add your handling code here:
        ArrayList<Producto> u = new ProductoDao().listarProducto();
        new ProductoDao().listarTabla(tblProducto, u);
    }//GEN-LAST:event_btnListarProductoActionPerformed

    private void comboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCategoriaActionPerformed

    private void btnSalirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirProductoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirProductoActionPerformed

    private void comboProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProveedorActionPerformed

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        // TODO add your handling code here:
        new CategoriaDao().eliminarCategoria(tblCategoria);
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarClienteActionPerformed
     ArrayList<Categoria> client = new CategoriaDao().listarCategoria();
        new CategoriaDao().listarTabla(tblCategoria, client);
    }//GEN-LAST:event_btnListarClienteActionPerformed

    private void btnSalirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirClienteActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_btnSalirClienteActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        // TODO add your handling code here:
        String nombre = txtCategoria.getText();
        
  //Cliente(int codigo, String nombre, String telefono, String email, String direccion      
        Categoria cat = new Categoria(nombre);
        new CategoriaDao().agregarCategoria(cat);
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnSalirProducto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirProducto2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirProducto2ActionPerformed

    private void btnAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProveedorActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombreProveedor.getText();
        String telefono = txtTelefonoProveedor.getText();
        String email = txtEmailProveedor.getText();
        String direccion = txtDireccionProveedor.getText();
        //Cliente(int codigo, String nombre, String telefono, String email, String direccion
            Proveedor client = new Proveedor(nombre, telefono, email, direccion);
            new ProveedorDao().agregarProveedor(client);
    }//GEN-LAST:event_btnAgregarProveedorActionPerformed

    private void btnListarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProveedorActionPerformed
        // TODO add your handling code here:
        ArrayList<Proveedor> prob = new ProveedorDao().listarProveedor();
        new ProveedorDao().listarTabla(tblProveedor, prob);
    }//GEN-LAST:event_btnListarProveedorActionPerformed

    private void btnEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProveedorActionPerformed
        // TODO add your handling code here:
        new ProveedorDao().eliminarProveedor(tblProveedor);
    }//GEN-LAST:event_btnEliminarProveedorActionPerformed

    private void btnEditaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditaProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditaProveedorActionPerformed

    private void txtDireccionProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionProveedorActionPerformed

    private void limpiarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarUsuarioActionPerformed
        // TODO add your handling code here:
        limpiarUsuarios();
    }//GEN-LAST:event_limpiarUsuarioActionPerformed

    private void limpiarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarProductoActionPerformed
        // TODO add your handling code here:
        limpiarProductos();
    }//GEN-LAST:event_limpiarProductoActionPerformed

    private void limpiarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarCategoriaActionPerformed
        // TODO add your handling code here:
        limpiarCategoria();
    }//GEN-LAST:event_limpiarCategoriaActionPerformed

    private void limpiarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarProveedorActionPerformed
        // TODO add your handling code here:
        limpiarProveedores();
    }//GEN-LAST:event_limpiarProveedorActionPerformed

    private void btnActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUsuarioActionPerformed
        // TODO add your handling code here:
        
        editarUsuario();
        btnAdd.setEnabled(true);
        btnActualizarUsuario.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnAdd.setEnabled(true);
            btnEliminar.setEnabled(true);
            btnEditar.setEnabled(true);
            btnCancelar.setEnabled(false);
            btnActualizarUsuario.setEnabled(false);
    }//GEN-LAST:event_btnActualizarUsuarioActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnActualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarProductoActionPerformed
        // TODO add your handling code here:
        editarProducto();
    }//GEN-LAST:event_btnActualizarProductoActionPerformed

    private void btnCancelarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProductoActionPerformed
        // TODO add your handling code here:
        cancelarProducto();
    }//GEN-LAST:event_btnCancelarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mantenimiento().setVisible(true);
            }
        });
    }
     public void cancelar()
    {
        UsuarioNombre.setText("");
        UsuarioApellido.setText("");
        NickName.setText("");
       UsuarioClave.setText("");
       btnActualizarUsuario.setEnabled(false);
       btnCancelar.setEnabled(false);
       btnAdd.setEnabled(true);
            btnEliminar.setEnabled(true);
            btnEditar.setEnabled(true);
            btnCancelar.setEnabled(false);
            btnActualizarUsuario.setEnabled(false);
       
    }
    public void cargarDatosUsuario()
    {
        
        int fila = usuarios.getSelectedRow();
        if(fila>=0)
        {
            UsuarioNombre.setText(String.valueOf(usuarios.getValueAt(fila, 1)));
            UsuarioApellido.setText(String.valueOf(usuarios.getValueAt(fila, 2)));
            NickName.setText(String.valueOf(usuarios.getValueAt(fila, 3)));
            UsuarioClave.setText(String.valueOf(usuarios.getValueAt(fila, 4)));
            Nivel.setSelectedItem(usuarios.getValueAt(fila, 5).toString());
            btnAdd.setEnabled(false);
            btnEliminar.setEnabled(false);
            btnEditar.setEnabled(false);
            btnCancelar.setEnabled(true);
            btnActualizarUsuario.setEnabled(true);
        }else
        {
            JOptionPane.showMessageDialog(null, "Debe de seleccionar un usuario");
        }
        /*
            String usuarioNombre = UsuarioNombre.getText();
                String usuarioApellido = UsuarioApellido.getText();
                String nick = NickName.getText();
                String clave = UsuarioClave.getText();
                int nivel = Nivel.getSelectedIndex()+1;
        
        */
    }
    
    public void editarUsuario()
    {
        try {
                int fila = usuarios.getSelectedRow();
                int id = (int)usuarios.getValueAt(fila, 0);
                String usuarioNombre = UsuarioNombre.getText();
                String usuarioApellido = UsuarioApellido.getText();
                String nick = NickName.getText();
                String clave = UsuarioClave.getText();
                int nivel = Nivel.getSelectedIndex()+1;


                Connection con = null;
                PreparedStatement ps = null;
                con = new BDatos().getConnection();
                String sql = "UPDATE `usuarios` SET `NICKNAME`=?,`CLAVE`=?,`NOMBRE`=?,`APELLIDO`=?,`NIVEL`=? WHERE ID = ?";
                ps = con.prepareStatement(sql);
                ps.setString(1, nick);
                ps.setString(2, clave);
                ps.setString(3, usuarioNombre);
                ps.setString(4, usuarioApellido);
                ps.setInt(5, nivel);
                ps.setInt(6, id);
                ps.execute();
                btnActualizarProducto.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Usuario Actualizado","Aviso", HEIGHT);
                
        } catch (SQLException ex) {
            Logger.getLogger(Mantenimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void cargarProducto()
    {
        int fila = tblProducto.getSelectedRow();
        if(fila >= 0)
        {
            
            txtProducto.setText(tblProducto.getValueAt(fila, 1).toString());
            txtDescripcion.setText(tblProducto.getValueAt(fila, 2).toString());
            comboCategoria.setSelectedItem(tblProducto.getValueAt(fila, 3).toString());
            comboProveedor.setSelectedItem(tblProducto.getValueAt(fila, 4).toString());
            //int valorVenta =
            //ARREGLAR ERROR DE CASTEO DE LOS INTEGER, PROBAR PASANDOLOS A INT Y LUEGO A STRING PARA VOLVERLOS PASAR A INT CON INTEGER.VALUEOF();
            txtPrecioVenta.setValue(Integer.valueOf(tblProducto.getValueAt(fila, 5).toString()));
            txtPrecioCompra.setValue(Integer.valueOf(tblProducto.getValueAt(fila, 6).toString()));
            txtCantidad.setValue(Integer.valueOf(tblProducto.getValueAt(fila, 7).toString()));
            java.util.Date date = (Date)tblProducto.getValueAt(fila, 8);
            fechaProducto.setDate(date);
            btnAgregarProducto.setEnabled(false);
            btnEliminarProducto.setEnabled(false);
            btnEditarProducto.setEnabled(false);
            btnActualizarProducto.setEnabled(true);
            btnCancelarProducto.setEnabled(true);
            
        }else
        {
            JOptionPane.showMessageDialog(null, "Selecciona un producto primero", "Aviso", HEIGHT);
        }
        
    }
    public void cancelarProducto()
    {
          txtProducto.setText("");
        txtDescripcion.setText("");
        
        txtCantidadOff.setText("");
        
        txtPrecioVentaOff.setText("");
        txtPrecioCompraOff.setText("");
       btnAgregarProducto.setEnabled(true);
            btnEliminarProducto.setEnabled(true);
            btnEditarProducto.setEnabled(true);
            btnActualizarProducto.setEnabled(false);
            btnCancelarProducto.setEnabled(false);
    }
                
    public int idCategoria(String categoria)
    {
            int idCategoria = 0;    
        try {
            
            Connection con2 = null;
            PreparedStatement ps2 = null;
            ResultSet rs = null;
            con2 = new BDatos().getConnection();
            String query = "SELECT `ID_CATEGORIA` FROM `categoria` WHERE NOMBRE = ?";
            ps2 = con2.prepareStatement(query);
            ps2.setString(1, categoria);
            rs = ps2.executeQuery();
            while(rs.next())
            {
                idCategoria = rs.getInt(1);
            }
           
        } catch (SQLException ex) {
            Logger.getLogger(Mantenimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
         return idCategoria;
    }
    
    public int idProveedor(String proveedor)
    {
        int idProveedor = 0;
        try {
            
            Connection con3 = null;
            con3 = new BDatos().getConnection();
            PreparedStatement ps3;
            ResultSet rs2;
            String query2 = "SELECT `ID_PROVEEDOR` FROM `proveedor` WHERE NOMBRE = ?";
            ps3 = con3.prepareStatement(query2);
            ps3.setString(1, proveedor);
            rs2 = ps3.executeQuery();
            while(rs2.next())
            {
                idProveedor = rs2.getInt(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Mantenimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
        return idProveedor;        
    }
    public void editarProducto()
    {
        try {
                int fila = tblProducto.getSelectedRow();
                int id = (int)tblProducto.getValueAt(fila, 0);
                String nombre = txtProducto.getText();
                String descripcion = txtDescripcion.getText();
                String categoria = comboCategoria.getSelectedItem().toString();
                String proveedor = comboProveedor.getSelectedItem().toString();
                int cant = (int)txtCantidad.getValue();
                
                //int cantidad = Integer.parseInt(cant);
                double precio_venta = (int)txtPrecioVenta.getValue();
                double precio_compra = (int)txtPrecioCompra.getValue();
                //java.util.Date cast = fechaProducto.getDate();
                
                
                
                
                
                
                Connection con = null;
                PreparedStatement ps = null;
                con = new BDatos().getConnection();
                String sql = "UPDATE `producto` SET `NOMBRE`=?,`DESCRIPCION`=?,`ID_CATEGORIA`=?,`ID_PROVEEDOR`=?,`PRECIO_VENTA`=?,`PRECIO_COMPRA`=?,`CANTIDAD`=? WHERE ID_PRODUCTO = ?";
                ps = con.prepareStatement(sql);
                ps.setString(1, nombre);
                ps.setString(2, descripcion);
                ps.setInt(3, idCategoria(categoria));
                ps.setInt(4, idProveedor(proveedor));
                ps.setDouble(5, precio_venta);
                ps.setDouble(6, precio_compra);
                ps.setInt(7, cant);
                ps.setInt(8, id);
                ps.execute();
                /*
                int fila = tblProducto.getSelectedRow();
                int id = (int)tblProducto.getValueAt(fila, 0);
                String nombre = txtProducto.getText();
                String descripcion = txtDescripcion.getText();
                String categoria = comboCategoria.getSelectedItem().toString();
                String proveedor = comboProveedor.getSelectedItem().toString();
                String cant = txtCantidad.getText();
                int cantidad = Integer.parseInt(cant);
                double precio_venta = Double.valueOf(txtPrecioVenta.getText());
                double precio_compra = Double.valueOf(txtPrecioCompra.getText());
                java.util.Date cast = fechaProducto.getDate();
                
                */
                JOptionPane.showMessageDialog(null, "Producto Actualizado","Aviso", HEIGHT);
                btnActualizarUsuario.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(Mantenimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
            
    public javax.swing.JTable getProducto()
    {
        return tblProducto;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField NickName;
    public javax.swing.JComboBox<String> Nivel;
    private javax.swing.JPanel PanelCliente;
    private javax.swing.JPanel PanelProducto;
    private javax.swing.JPanel PanelUsuarios;
    private javax.swing.JTabbedPane PestanasMantenimiento;
    private javax.swing.JPanel Proveedores;
    private javax.swing.JScrollPane ScrollUsuarios;
    private javax.swing.JScrollPane ScrollUsuarios3;
    private javax.swing.JScrollPane ScrollUsuarios4;
    private javax.swing.JScrollPane ScrollUsuarios5;
    public javax.swing.JTextField UsuarioApellido;
    public javax.swing.JPasswordField UsuarioClave;
    public javax.swing.JTextField UsuarioNombre;
    private javax.swing.JButton btnActualizarProducto;
    private javax.swing.JButton btnActualizarUsuario;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnAgregarProveedor;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarProducto;
    public javax.swing.JButton btnEditaProveedor;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEditar1;
    public javax.swing.JButton btnEditarCliente;
    public javax.swing.JButton btnEditarProducto;
    public static javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnEliminarCliente;
    public javax.swing.JButton btnEliminarProducto;
    public javax.swing.JButton btnEliminarProveedor;
    public javax.swing.JButton btnListar;
    public javax.swing.JButton btnListarCliente;
    public javax.swing.JButton btnListarProducto;
    public javax.swing.JButton btnListarProveedor;
    public static final javax.swing.JButton btnSalir = new javax.swing.JButton();
    public static final javax.swing.JButton btnSalirCliente = new javax.swing.JButton();
    public static final javax.swing.JButton btnSalirProducto = new javax.swing.JButton();
    public static final javax.swing.JButton btnSalirProducto2 = new javax.swing.JButton();
    public javax.swing.JComboBox<String> comboCategoria;
    public javax.swing.JComboBox<String> comboProveedor;
    private com.toedter.calendar.JDateChooser fechaProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton limpiarCategoria;
    private javax.swing.JButton limpiarProducto;
    private javax.swing.JButton limpiarProveedor;
    private javax.swing.JButton limpiarUsuario;
    public javax.swing.JTable tblCategoria;
    public javax.swing.JTable tblProducto;
    public javax.swing.JTable tblProveedor;
    private javax.swing.JSpinner txtCantidad;
    public javax.swing.JTextField txtCantidadOff;
    public javax.swing.JTextField txtCategoria;
    public javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDireccionProveedor;
    public javax.swing.JTextField txtEmailProveedor;
    public javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JSpinner txtPrecioCompra;
    public javax.swing.JTextField txtPrecioCompraOff;
    private javax.swing.JSpinner txtPrecioVenta;
    public javax.swing.JTextField txtPrecioVentaOff;
    public javax.swing.JTextField txtProducto;
    public javax.swing.JTextField txtTelefonoProveedor;
    public javax.swing.JTable usuarios;
    // End of variables declaration//GEN-END:variables
}
