/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

//import static Vista.Menu.HoraActual;
import static Vista.Menu.UsuarioActual;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;

/**
 *
 * @author Jhonas
 */
public class MenuInvitado extends javax.swing.JFrame implements Runnable{
String hora, minuto, segundo, ampm;
    Calendar calendario;
    Thread h1;
    /**
     * Creates new form MenuInvitado
     */
    public MenuInvitado() {
        initComponents();
        h1 = new Thread(this);
        h1.start();
        setLocationRelativeTo(null);
        URL url = getClass().getResource("/Vista/Iconos UI/logoFrame.png");
        ImageIcon img = new ImageIcon(url);
        setIconImage(img.getImage());
        /*Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Vista/Iconos UI/logoFrame.png"));
        setIconImage(icon);
        setVisible(true);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Reloj1 = new javax.swing.JSeparator();
        Reloj = new javax.swing.JSeparator();
        Aside = new javax.swing.JPanel();
        PanelMenuConsulta = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelMenuConfiguracion1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnReporte = new javax.swing.JButton();
        btnMantenimiento = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FechaActual.setEditable(false);
        FechaActual.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        FechaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaActualActionPerformed(evt);
            }
        });
        jPanel2.add(FechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 140, 30));

        UsuarioActualInvitado.setEditable(false);
        UsuarioActualInvitado.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        UsuarioActualInvitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActualInvitadoActionPerformed(evt);
            }
        });
        jPanel2.add(UsuarioActualInvitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsuarioActual1.setEditable(false);
        UsuarioActual1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jPanel3.add(UsuarioActual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        FechaActual1.setEditable(false);
        FechaActual1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        FechaActual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaActual1ActionPerformed(evt);
            }
        });
        jPanel3.add(FechaActual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 140, 30));

        Reloj1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(Reloj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 1100, 10));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1110, -1));

        Reloj.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Reloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 10));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1110, 30));

        Aside.setBackground(new java.awt.Color(22, 160, 133));
        Aside.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMenuConsulta.setBackground(new java.awt.Color(26, 188, 156));
        PanelMenuConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMenuConsultaMouseClicked(evt);
            }
        });
        PanelMenuConsulta.setLayout(new javax.swing.BoxLayout(PanelMenuConsulta, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos UI/Consulta_32px.png"))); // NOI18N
        PanelMenuConsulta.add(jLabel3);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("              CONSULTAS");
        PanelMenuConsulta.add(jLabel2);

        Aside.add(PanelMenuConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 260, 60));

        PanelMenuConfiguracion1.setBackground(new java.awt.Color(30, 193, 160));
        PanelMenuConfiguracion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMenuConfiguracion1MouseClicked(evt);
            }
        });
        PanelMenuConfiguracion1.setLayout(new javax.swing.BoxLayout(PanelMenuConfiguracion1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos UI/Salir_32px.png"))); // NOI18N
        PanelMenuConfiguracion1.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("              SALIR");
        PanelMenuConfiguracion1.add(jLabel11);

        Aside.add(PanelMenuConfiguracion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 260, 60));

        btnReporte.setBackground(new java.awt.Color(255, 255, 255));
        btnReporte.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(0, 204, 51));
        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/MENU ICONS/Reporte-verde.png"))); // NOI18N
        btnReporte.setText("REPORTES");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        Aside.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        btnMantenimiento.setBackground(new java.awt.Color(255, 255, 255));
        btnMantenimiento.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMantenimiento.setForeground(new java.awt.Color(0, 204, 51));
        btnMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/MENU ICONS/Mantenimiento-verde.png"))); // NOI18N
        btnMantenimiento.setText("MANTENIMIENTO");
        btnMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoActionPerformed(evt);
            }
        });
        Aside.add(btnMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        btnConsultas.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultas.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnConsultas.setForeground(new java.awt.Color(0, 204, 51));
        btnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/MENU ICONS/consulta-verde.png"))); // NOI18N
        btnConsultas.setText("CONSULTAS");
        Aside.add(btnConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, -1));

        btnConfiguracion.setBackground(new java.awt.Color(255, 255, 255));
        btnConfiguracion.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnConfiguracion.setForeground(new java.awt.Color(0, 204, 51));
        btnConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/MENU ICONS/Config.png"))); // NOI18N
        btnConfiguracion.setText("CONFIGURACION");
        Aside.add(btnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 190, 40));

        background.add(Aside, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 500));

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INLAP SOFTWARE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 200, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/menuFoto.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -20, 350, 260));

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 820, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FechaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaActualActionPerformed

    private void FechaActual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaActual1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaActual1ActionPerformed

    private void PanelMenuConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuConsultaMouseClicked
        // TODO add your handling code here:
        new Consultas().setVisible(true);
    }//GEN-LAST:event_PanelMenuConsultaMouseClicked

    private void PanelMenuConfiguracion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuConfiguracion1MouseClicked
        // TODO add your handling code here:
        this.dispose();

        new Login().setVisible(true);
    }//GEN-LAST:event_PanelMenuConfiguracion1MouseClicked

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoActionPerformed
        // TODO add your handling code here:
        new Mantenimiento().setVisible(true);
    }//GEN-LAST:event_btnMantenimientoActionPerformed

    private void UsuarioActualInvitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActualInvitadoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_UsuarioActualInvitadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInvitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInvitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInvitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInvitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInvitado().setVisible(true);
            }
        });
    }
public javax.swing.JTextField getUsuarioActual()
    {
        return UsuarioActualInvitado;
    }
    
public javax.swing.JTextField getFechaActual()
{
    return FechaActual;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Aside;
    public static final javax.swing.JTextField FechaActual = new javax.swing.JTextField();
    public static final javax.swing.JTextField FechaActual1 = new javax.swing.JTextField();
    private javax.swing.JPanel PanelMenuConfiguracion1;
    private javax.swing.JPanel PanelMenuConsulta;
    private javax.swing.JSeparator Reloj;
    private javax.swing.JSeparator Reloj1;
    public static final javax.swing.JTextField UsuarioActual1 = new javax.swing.JTextField();
    public static final javax.swing.JTextField UsuarioActualInvitado = new javax.swing.JTextField();
    private javax.swing.JPanel background;
    public javax.swing.JButton btnConfiguracion;
    public javax.swing.JButton btnConsultas;
    public javax.swing.JButton btnMantenimiento;
    public javax.swing.JButton btnReporte;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        Thread ct = Thread.currentThread();
        while(ct==h1)
        {
           calcula();
           //hora+":"+
       //    HoraActual.setText(hora+":"+minuto+":"+segundo+" "+ampm);
           try
           {
               Thread.sleep(1000);
           }catch(InterruptedException e)
           {
               
           }
        }
    }
 //Calendar calendario = Calendar.getInstance();
    private void calcula() {
        Calendar calendario = new GregorianCalendar();
       
        Date fechaActual = new Date();
        
        calendario.setTime(fechaActual);
        ampm = calendario.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";
        if(ampm.equals("PM"))
        {
            int h = calendario.get(Calendar.HOUR_OF_DAY);
            hora = h>9?""+h1:"0"+h;
            
        }else
        {
            hora = calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        }
        minuto = calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundo = calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }

}
