/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.BDatosDao;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.net.URL;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Jhonas
 */
public class Menu extends javax.swing.JFrame implements Runnable {
    String hora, minuto, segundo, ampm;
    Calendar calendario;
    Thread h1;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        h1 = new Thread(this);
        h1.start();
        setLocationRelativeTo(null);
        URL url = getClass().getResource("/Vista/Iconos UI/logoFrame.png");
        ImageIcon img = new ImageIcon(url);
        setIconImage(img.getImage());
        /*Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Vista/Iconos UI/logoFrame.png"));
        setIconImage(icon);
        setVisible(true);*/
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Reloj1 = new javax.swing.JSeparator();
        Reloj = new javax.swing.JSeparator();
        Aside = new javax.swing.JPanel();
        PanelMenuConsulta = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelMenuReportes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PanelMenuMantenimiento = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PanelMenuConfiguracion1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnReporte = new javax.swing.JButton();
        btnMantenimiento = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        PanelMenuMovimiento = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        background1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Reloj2 = new javax.swing.JSeparator();
        Reloj3 = new javax.swing.JSeparator();
        Aside1 = new javax.swing.JPanel();
        PanelMenuConsulta1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PanelMenuReportes1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        PanelMenuMantenimiento1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        PanelMenuConfiguracion2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnReporte1 = new javax.swing.JButton();
        btnMantenimiento1 = new javax.swing.JButton();
        btnConsultas1 = new javax.swing.JButton();
        btnConfiguracion1 = new javax.swing.JButton();
        PanelMenuMovimiento1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu");
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FechaActual.setEditable(false);
        FechaActual.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        FechaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaActualActionPerformed(evt);
            }
        });
        jPanel2.add(FechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 140, 30));

        UsuarioActual.setEditable(false);
        UsuarioActual.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        UsuarioActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActualActionPerformed(evt);
            }
        });
        jPanel2.add(UsuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsuarioActual1.setEditable(false);
        UsuarioActual1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jPanel3.add(UsuarioActual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        FechaActual1.setEditable(false);
        FechaActual1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        FechaActual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaActual1ActionPerformed(evt);
            }
        });
        jPanel3.add(FechaActual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 140, 30));

        Reloj1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(Reloj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 1100, 10));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1110, -1));

        Reloj.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Reloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 10));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1110, 30));

        Aside.setBackground(new java.awt.Color(22, 160, 133));
        Aside.setToolTipText("Reportes");
        Aside.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMenuConsulta.setBackground(new java.awt.Color(26, 188, 156));
        PanelMenuConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMenuConsultaMouseClicked(evt);
            }
        });
        PanelMenuConsulta.setLayout(new javax.swing.BoxLayout(PanelMenuConsulta, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos UI/Consulta_32px.png"))); // NOI18N
        PanelMenuConsulta.add(jLabel3);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("              CONSULTAS");
        PanelMenuConsulta.add(jLabel2);

        Aside.add(PanelMenuConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 260, 60));

        PanelMenuReportes.setBackground(new java.awt.Color(30, 193, 160));
        PanelMenuReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMenuReportesMouseClicked(evt);
            }
        });
        PanelMenuReportes.setLayout(new javax.swing.BoxLayout(PanelMenuReportes, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos UI/Reportes_32px.png"))); // NOI18N
        PanelMenuReportes.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("              REPORTES");
        PanelMenuReportes.add(jLabel5);

        Aside.add(PanelMenuReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 260, 60));

        PanelMenuMantenimiento.setBackground(new java.awt.Color(30, 193, 160));
        PanelMenuMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMenuMantenimientoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelMenuMantenimientoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelMenuMantenimientoMouseExited(evt);
            }
        });
        PanelMenuMantenimiento.setLayout(new javax.swing.BoxLayout(PanelMenuMantenimiento, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos UI/Mantenimiento_32px.png"))); // NOI18N
        PanelMenuMantenimiento.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("              MANTENIMIENTO");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });
        PanelMenuMantenimiento.add(jLabel7);

        Aside.add(PanelMenuMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 260, 60));

        PanelMenuConfiguracion1.setBackground(new java.awt.Color(30, 193, 160));
        PanelMenuConfiguracion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMenuConfiguracion1MouseClicked(evt);
            }
        });
        PanelMenuConfiguracion1.setLayout(new javax.swing.BoxLayout(PanelMenuConfiguracion1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos UI/Salir_32px.png"))); // NOI18N
        PanelMenuConfiguracion1.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("              SALIR");
        PanelMenuConfiguracion1.add(jLabel11);

        Aside.add(PanelMenuConfiguracion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 260, 60));

        btnReporte.setBackground(new java.awt.Color(255, 255, 255));
        btnReporte.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(0, 204, 51));
        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/MENU ICONS/Reporte-verde.png"))); // NOI18N
        btnReporte.setText("REPORTES");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        Aside.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        btnMantenimiento.setBackground(new java.awt.Color(255, 255, 255));
        btnMantenimiento.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMantenimiento.setForeground(new java.awt.Color(0, 204, 51));
        btnMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/MENU ICONS/Mantenimiento-verde.png"))); // NOI18N
        btnMantenimiento.setText("MANTENIMIENTO");
        btnMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoActionPerformed(evt);
            }
        });
        Aside.add(btnMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        btnConsultas.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultas.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnConsultas.setForeground(new java.awt.Color(0, 204, 51));
        btnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/MENU ICONS/consulta-verde.png"))); // NOI18N
        btnConsultas.setText("CONSULTAS");
        Aside.add(btnConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, -1));

        btnConfiguracion.setBackground(new java.awt.Color(255, 255, 255));
        btnConfiguracion.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnConfiguracion.setForeground(new java.awt.Color(0, 204, 51));
        btnConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/MENU ICONS/Config.png"))); // NOI18N
        btnConfiguracion.setText("CONFIGURACION");
        Aside.add(btnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 190, 40));

        PanelMenuMovimiento.setBackground(new java.awt.Color(30, 193, 160));
        PanelMenuMovimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMenuMovimientoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelMenuMovimientoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelMenuMovimientoMouseExited(evt);
            }
        });
        PanelMenuMovimiento.setLayout(new javax.swing.BoxLayout(PanelMenuMovimiento, javax.swing.BoxLayout.LINE_AXIS));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/camion-de-entrega-de-la-logistica-en-el-movimiento.png"))); // NOI18N
        PanelMenuMovimiento.add(jLabel9);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("      MOVIMIENTOS");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
        });
        PanelMenuMovimiento.add(jLabel12);

        Aside.add(PanelMenuMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 260, 60));

        background.add(Aside, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 500));

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/menuFoto.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, -10, 350, 260));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INLAP SOFTWARE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 200, 50));

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 820, 240));

        background1.setBackground(new java.awt.Color(255, 255, 255));
        background1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FechaActual2.setEditable(false);
        FechaActual2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        FechaActual2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaActual2ActionPerformed(evt);
            }
        });
        jPanel4.add(FechaActual2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 140, 30));

        UsuarioActual2.setEditable(false);
        UsuarioActual2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        UsuarioActual2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActual2ActionPerformed(evt);
            }
        });
        jPanel4.add(UsuarioActual2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        HoraActual2.setEditable(false);
        HoraActual2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        HoraActual2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraActual2ActionPerformed(evt);
            }
        });
        jPanel4.add(HoraActual2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 150, 30));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsuarioActual3.setEditable(false);
        UsuarioActual3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jPanel5.add(UsuarioActual3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        FechaActual3.setEditable(false);
        FechaActual3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        FechaActual3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaActual3ActionPerformed(evt);
            }
        });
        jPanel5.add(FechaActual3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 140, 30));

        Reloj2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(Reloj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 1100, 10));

        HoraActual3.setEditable(false);
        HoraActual3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        HoraActual3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraActual3ActionPerformed(evt);
            }
        });
        jPanel5.add(HoraActual3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 140, 30));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1110, -1));

        Reloj3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(Reloj3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 10));

        background1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1110, 30));

        Aside1.setBackground(new java.awt.Color(22, 160, 133));
        Aside1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMenuConsulta1.setBackground(new java.awt.Color(26, 188, 156));
        PanelMenuConsulta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMenuConsulta1MouseClicked(evt);
            }
        });
        PanelMenuConsulta1.setLayout(new javax.swing.BoxLayout(PanelMenuConsulta1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos UI/Consulta_32px.png"))); // NOI18N
        PanelMenuConsulta1.add(jLabel13);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("              CONSULTAS");
        PanelMenuConsulta1.add(jLabel14);

        Aside1.add(PanelMenuConsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 260, 60));

        PanelMenuReportes1.setBackground(new java.awt.Color(30, 193, 160));
        PanelMenuReportes1.setLayout(new javax.swing.BoxLayout(PanelMenuReportes1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos UI/Reportes_32px.png"))); // NOI18N
        PanelMenuReportes1.add(jLabel15);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("              REPORTES");
        PanelMenuReportes1.add(jLabel16);

        Aside1.add(PanelMenuReportes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 260, 60));

        PanelMenuMantenimiento1.setBackground(new java.awt.Color(30, 193, 160));
        PanelMenuMantenimiento1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMenuMantenimiento1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelMenuMantenimiento1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelMenuMantenimiento1MouseExited(evt);
            }
        });
        PanelMenuMantenimiento1.setLayout(new javax.swing.BoxLayout(PanelMenuMantenimiento1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos UI/Mantenimiento_32px.png"))); // NOI18N
        PanelMenuMantenimiento1.add(jLabel17);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("              MANTENIMIENTO");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
        });
        PanelMenuMantenimiento1.add(jLabel18);

        Aside1.add(PanelMenuMantenimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 260, 60));

        PanelMenuConfiguracion2.setBackground(new java.awt.Color(30, 193, 160));
        PanelMenuConfiguracion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMenuConfiguracion2MouseClicked(evt);
            }
        });
        PanelMenuConfiguracion2.setLayout(new javax.swing.BoxLayout(PanelMenuConfiguracion2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos UI/Salir_32px.png"))); // NOI18N
        PanelMenuConfiguracion2.add(jLabel19);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("              SALIR");
        PanelMenuConfiguracion2.add(jLabel20);

        Aside1.add(PanelMenuConfiguracion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 260, 60));

        btnReporte1.setBackground(new java.awt.Color(255, 255, 255));
        btnReporte1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnReporte1.setForeground(new java.awt.Color(0, 204, 51));
        btnReporte1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/MENU ICONS/Reporte-verde.png"))); // NOI18N
        btnReporte1.setText("REPORTES");
        btnReporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporte1ActionPerformed(evt);
            }
        });
        Aside1.add(btnReporte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        btnMantenimiento1.setBackground(new java.awt.Color(255, 255, 255));
        btnMantenimiento1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMantenimiento1.setForeground(new java.awt.Color(0, 204, 51));
        btnMantenimiento1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/MENU ICONS/Mantenimiento-verde.png"))); // NOI18N
        btnMantenimiento1.setText("MANTENIMIENTO");
        btnMantenimiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimiento1ActionPerformed(evt);
            }
        });
        Aside1.add(btnMantenimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        btnConsultas1.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultas1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnConsultas1.setForeground(new java.awt.Color(0, 204, 51));
        btnConsultas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/MENU ICONS/consulta-verde.png"))); // NOI18N
        btnConsultas1.setText("CONSULTAS");
        Aside1.add(btnConsultas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, -1));

        btnConfiguracion1.setBackground(new java.awt.Color(255, 255, 255));
        btnConfiguracion1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnConfiguracion1.setForeground(new java.awt.Color(0, 204, 51));
        btnConfiguracion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/MENU ICONS/Config.png"))); // NOI18N
        btnConfiguracion1.setText("CONFIGURACION");
        Aside1.add(btnConfiguracion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 190, 40));

        PanelMenuMovimiento1.setBackground(new java.awt.Color(30, 193, 160));
        PanelMenuMovimiento1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMenuMovimiento1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelMenuMovimiento1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelMenuMovimiento1MouseExited(evt);
            }
        });
        PanelMenuMovimiento1.setLayout(new javax.swing.BoxLayout(PanelMenuMovimiento1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("              MANTENIMIENTO");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21MouseEntered(evt);
            }
        });
        PanelMenuMovimiento1.add(jLabel21);

        Aside1.add(PanelMenuMovimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 260, 60));

        background1.add(Aside1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 500));

        jPanel6.setBackground(new java.awt.Color(52, 152, 219));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/menuFoto.png"))); // NOI18N
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -20, 350, 260));

        background1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 820, 240));

        background.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 530));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 530));

        getAccessibleContext().setAccessibleName("Menu ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FechaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaActualActionPerformed

    private void FechaActual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaActual1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaActual1ActionPerformed

    private void btnMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoActionPerformed
        // TODO add your handling code here:
        new Mantenimiento().setVisible(true);
    }//GEN-LAST:event_btnMantenimientoActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteActionPerformed

    private void PanelMenuConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuConsultaMouseClicked
        // TODO add your handling code here:
        new Consultas().setVisible(true);
    }//GEN-LAST:event_PanelMenuConsultaMouseClicked

    private void PanelMenuMantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuMantenimientoMouseClicked
        // TODO add your handling code here:
        new Mantenimiento().setVisible(true);
    }//GEN-LAST:event_PanelMenuMantenimientoMouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void PanelMenuMantenimientoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuMantenimientoMouseEntered
        // TODO add your handling code here:
       //Color color = Color.getHSBColor(168, 86, 74);
              
      
       
    }//GEN-LAST:event_PanelMenuMantenimientoMouseEntered

    private void PanelMenuMantenimientoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuMantenimientoMouseExited
        // TODO add your handling code here:
        //[30,193,160]
        
        
    }//GEN-LAST:event_PanelMenuMantenimientoMouseExited

    private void PanelMenuConfiguracion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuConfiguracion1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        
        new Login().setVisible(true);
    }//GEN-LAST:event_PanelMenuConfiguracion1MouseClicked

    private void UsuarioActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActualActionPerformed

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseEntered

    private void PanelMenuMovimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuMovimientoMouseClicked
        // TODO add your handling code here:
      new Movimientos().setVisible(true);
    }//GEN-LAST:event_PanelMenuMovimientoMouseClicked

    private void PanelMenuMovimientoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuMovimientoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMenuMovimientoMouseEntered

    private void PanelMenuMovimientoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuMovimientoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMenuMovimientoMouseExited

    private void FechaActual2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaActual2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaActual2ActionPerformed

    private void UsuarioActual2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActual2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActual2ActionPerformed

    private void HoraActual2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoraActual2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoraActual2ActionPerformed

    private void FechaActual3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaActual3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaActual3ActionPerformed

    private void HoraActual3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoraActual3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoraActual3ActionPerformed

    private void PanelMenuConsulta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuConsulta1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMenuConsulta1MouseClicked

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseEntered

    private void PanelMenuMantenimiento1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuMantenimiento1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMenuMantenimiento1MouseClicked

    private void PanelMenuMantenimiento1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuMantenimiento1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMenuMantenimiento1MouseEntered

    private void PanelMenuMantenimiento1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuMantenimiento1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMenuMantenimiento1MouseExited

    private void PanelMenuConfiguracion2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuConfiguracion2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMenuConfiguracion2MouseClicked

    private void btnReporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporte1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporte1ActionPerformed

    private void btnMantenimiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimiento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMantenimiento1ActionPerformed

    private void jLabel21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseEntered

    private void PanelMenuMovimiento1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuMovimiento1MouseClicked
        // TODO add your handling code here:
        new Movimientos().setVisible(true);
    }//GEN-LAST:event_PanelMenuMovimiento1MouseClicked

    private void PanelMenuMovimiento1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuMovimiento1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMenuMovimiento1MouseEntered

    private void PanelMenuMovimiento1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuMovimiento1MouseExited
        
        
        
        
        
        
        
    }//GEN-LAST:event_PanelMenuMovimiento1MouseExited

    private void PanelMenuReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuReportesMouseClicked
        // TODO add your handling code here:
        new Reportes().setVisible(true);
    }//GEN-LAST:event_PanelMenuReportesMouseClicked
    
    /*public void mouseEntered(MouseEvent e) {
    JPanel parent = (JPanel)e.getSource();
    parent.setBorder(grayBorder);
    parent.revalidate();
}*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    public javax.swing.JTextField getUsuarioActual()
    {
        return UsuarioActual;
    }
    
    public javax.swing.JTextField getFechaActual()
    {
        return FechaActual;
    }
    
    /*public javax.swing.JTextField getHoraActual()
    {
        return HoraActual;
    }
*/
    public JButton getBtnConfiguracion() {
        return btnConfiguracion;
    }

    public JButton getBtnConsultas() {
        return btnConsultas;
    }

    public JButton getBtnMantenimiento() {
        return btnMantenimiento;
    }

    public JButton getBtnReporte() {
        return btnReporte;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Aside;
    private javax.swing.JPanel Aside1;
    public static final javax.swing.JTextField FechaActual = new javax.swing.JTextField();
    public static final javax.swing.JTextField FechaActual1 = new javax.swing.JTextField();
    public static final javax.swing.JTextField FechaActual2 = new javax.swing.JTextField();
    public static final javax.swing.JTextField FechaActual3 = new javax.swing.JTextField();
    public static final javax.swing.JTextField HoraActual2 = new javax.swing.JTextField();
    public static final javax.swing.JTextField HoraActual3 = new javax.swing.JTextField();
    private javax.swing.JPanel PanelMenuConfiguracion1;
    private javax.swing.JPanel PanelMenuConfiguracion2;
    private javax.swing.JPanel PanelMenuConsulta;
    private javax.swing.JPanel PanelMenuConsulta1;
    private javax.swing.JPanel PanelMenuMantenimiento;
    private javax.swing.JPanel PanelMenuMantenimiento1;
    private javax.swing.JPanel PanelMenuMovimiento;
    private javax.swing.JPanel PanelMenuMovimiento1;
    private javax.swing.JPanel PanelMenuReportes;
    private javax.swing.JPanel PanelMenuReportes1;
    private javax.swing.JSeparator Reloj;
    private javax.swing.JSeparator Reloj1;
    private javax.swing.JSeparator Reloj2;
    private javax.swing.JSeparator Reloj3;
    public static final javax.swing.JTextField UsuarioActual = new javax.swing.JTextField();
    public static final javax.swing.JTextField UsuarioActual1 = new javax.swing.JTextField();
    public static final javax.swing.JTextField UsuarioActual2 = new javax.swing.JTextField();
    public static final javax.swing.JTextField UsuarioActual3 = new javax.swing.JTextField();
    private javax.swing.JPanel background;
    private javax.swing.JPanel background1;
    public javax.swing.JButton btnConfiguracion;
    public javax.swing.JButton btnConfiguracion1;
    public javax.swing.JButton btnConsultas;
    public javax.swing.JButton btnConsultas1;
    public javax.swing.JButton btnMantenimiento;
    public javax.swing.JButton btnMantenimiento1;
    public javax.swing.JButton btnReporte;
    public javax.swing.JButton btnReporte1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        Thread ct = Thread.currentThread();
        while(ct==h1)
        {
           calcula();
           //hora+":"+
           //HoraActual.setText(hora+":"+minuto+":"+segundo+" "+ampm);
           try
           {
               Thread.sleep(1000);
           }catch(InterruptedException e)
           {
               
           }
        }
    }
 //Calendar calendario = Calendar.getInstance();
    private void calcula() {
        Calendar calendario = new GregorianCalendar();
       
        Date fechaActual = new Date();
        
        calendario.setTime(fechaActual);
        ampm = calendario.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";
        if(ampm.equals("PM"))
        {
            int h = calendario.get(Calendar.HOUR_OF_DAY);
            hora = h>9?""+h1:"0"+h;
            
        }else
        { 
            hora = calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        }
        minuto = calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundo = calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }
}
