/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Movimiento;
import Modelo.MovimientosDao;
import java.util.ArrayList;

/**
 *
 * @author Jhonas
 */
public class Movimientos extends javax.swing.JFrame {

    /**
     * Creates new form Movimientos
     */
    public Movimientos() {
        initComponents();
        ArrayList<Movimiento> u = new MovimientosDao().listaTablaMovimientos();
        new MovimientosDao().listarTabla(tblProductoMovimientos, u);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        ScrollUsuarios3 = new javax.swing.JScrollPane();
        tblProductoMovimientos = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        btnEditar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnEntrada = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        SpinnerCantidad = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Movimientos");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalirProducto.setBackground(new java.awt.Color(255, 255, 255));
        btnSalirProducto.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSalirProducto.setForeground(new java.awt.Color(0, 153, 0));
        btnSalirProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/salida.png"))); // NOI18N
        btnSalirProducto.setText("SALIR");
        btnSalirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirProductoActionPerformed(evt);
            }
        });
        jPanel7.add(btnSalirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, -1, -1));

        ScrollUsuarios3.setBackground(new java.awt.Color(255, 255, 255));

        tblProductoMovimientos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblProductoMovimientos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblProductoMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOMBRE", "DESCRIPCIÓN", "CATEGORÍA", "PROVEEDOR", "PRECIO DE COMPRA", "PRECIO DE VENTA", "FECHA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductoMovimientos.setGridColor(new java.awt.Color(255, 255, 255));
        tblProductoMovimientos.setIntercellSpacing(new java.awt.Dimension(5, 5));
        ScrollUsuarios3.setViewportView(tblProductoMovimientos);

        jPanel7.add(ScrollUsuarios3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 990, 190));

        jPanel12.setBackground(new java.awt.Color(22, 160, 133));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 580));

        btnEditar1.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEditar1.setForeground(new java.awt.Color(0, 153, 0));
        btnEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/edit-user.png"))); // NOI18N
        btnEditar1.setText("EDITAR");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });
        jPanel7.add(btnEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 40));

        jPanel1.setBackground(new java.awt.Color(22, 160, 133));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Movimientos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEntrada.setBackground(new java.awt.Color(255, 255, 255));
        btnEntrada.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEntrada.setForeground(new java.awt.Color(0, 153, 0));
        btnEntrada.setText("ENTRADA PRODUCTO");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 181, 67));

        btnSalida.setBackground(new java.awt.Color(255, 255, 255));
        btnSalida.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSalida.setForeground(new java.awt.Color(0, 153, 0));
        btnSalida.setText("SALIDA PRODUCTO");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 180, 70));
        jPanel1.add(SpinnerCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 111, 67));

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 560, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirProductoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirProductoActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        // TODO add your handling code here:
        int cantidad = (int)SpinnerCantidad.getValue();
        new MovimientosDao().ingresoProducto(cantidad, tblProductoMovimientos);
        ArrayList<Movimiento> u = new MovimientosDao().listaTablaMovimientos();
       
        new MovimientosDao().listarTabla(tblProductoMovimientos, u);
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        // TODO add your handling code here:
        int cantidad = (int)SpinnerCantidad.getValue();
         new MovimientosDao().salidaProducto(cantidad, tblProductoMovimientos);
         ArrayList<Movimiento> u = new MovimientosDao().listaTablaMovimientos();
        new MovimientosDao().listarTabla(tblProductoMovimientos, u);
    }//GEN-LAST:event_btnSalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Movimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollUsuarios3;
    private javax.swing.JSpinner SpinnerCantidad;
    public javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnSalida;
    public static final javax.swing.JButton btnSalirProducto = new javax.swing.JButton();
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel7;
    public javax.swing.JTable tblProductoMovimientos;
    // End of variables declaration//GEN-END:variables
}
