/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jhonas
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        btnEditar1 = new javax.swing.JButton();
        btnEntrada = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reportes");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(22, 160, 133));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 580));

        btnSalirProducto.setBackground(new java.awt.Color(255, 255, 255));
        btnSalirProducto.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSalirProducto.setForeground(new java.awt.Color(0, 153, 0));
        btnSalirProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/salida.png"))); // NOI18N
        btnSalirProducto.setText("SALIR");
        btnSalirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirProductoActionPerformed(evt);
            }
        });
        jPanel7.add(btnSalirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, -1, -1));

        btnEditar1.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEditar1.setForeground(new java.awt.Color(0, 153, 0));
        btnEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/CRUD/edit-user.png"))); // NOI18N
        btnEditar1.setText("EDITAR");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });
        jPanel7.add(btnEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 40));

        btnEntrada.setBackground(new java.awt.Color(255, 255, 255));
        btnEntrada.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEntrada.setForeground(new java.awt.Color(0, 153, 0));
        btnEntrada.setText("EXPORTAR INVENTARIO");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });
        jPanel7.add(btnEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 220, 67));

        btnSalida.setBackground(new java.awt.Color(255, 255, 255));
        btnSalida.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSalida.setForeground(new java.awt.Color(0, 153, 0));
        btnSalida.setText("DETALLE PRODUCTOs");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });
        jPanel7.add(btnSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 220, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirProductoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirProductoActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        // TODO add your handling code here:
        JTable tabla = new Consultas().getTablaConsulta();
     if(tabla.getRowCount()==0){
       JOptionPane.showMessageDialog(null, "Tabla vacia","Aviso",JOptionPane.INFORMATION_MESSAGE);
       }
       JFileChooser cho = new JFileChooser();
       FileNameExtensionFilter fl = new FileNameExtensionFilter("Archivos de excel","xls");
       cho.setFileFilter(fl);
       cho.setDialogTitle("Guardar archivo");
       cho.setMultiSelectionEnabled(false);
       cho.setAcceptAllFileFilterUsed(false);
       if(cho.showSaveDialog(null)==JFileChooser.APPROVE_OPTION){
           List<JTable> tb = new ArrayList<>();
           List<String> nom = new ArrayList<>();
           tb.add(tabla);
           nom.add("Inventario");
           String file=cho.getSelectedFile().toString().concat(".xls");
        try{
           
            Reporter r = new Reporter(new File(file),tb,nom);
            if(r.reporter()){
                JOptionPane.showMessageDialog(null,"Reporte generado","Aviso",JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Hubo un error"+e.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
        }
       }
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        JTable tabla = new Mantenimiento().getProducto();
       if(tabla.getRowCount()==0){
       JOptionPane.showMessageDialog(null, "Tabla vacia","Aviso",JOptionPane.INFORMATION_MESSAGE);
       }
       JFileChooser cho = new JFileChooser();
       FileNameExtensionFilter fl = new FileNameExtensionFilter("Archivos de excel","xls");
       cho.setFileFilter(fl);
       cho.setDialogTitle("Guardar archivo");
       cho.setMultiSelectionEnabled(false);
       cho.setAcceptAllFileFilterUsed(false);
       if(cho.showSaveDialog(null)==JFileChooser.APPROVE_OPTION){
           List<JTable> tb = new ArrayList<>();
           List<String> nom = new ArrayList<>();
           tb.add(tabla);
           nom.add("Inventario");
           String file=cho.getSelectedFile().toString().concat(".xls");
        try{
           
            Reporter r = new Reporter(new File(file),tb,nom);
            if(r.reporter()){
                JOptionPane.showMessageDialog(null,"Reporte generado","Aviso",JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Hubo un error"+e.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
        }
       }
                                             

    }//GEN-LAST:event_btnSalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnSalida;
    public static final javax.swing.JButton btnSalirProducto = new javax.swing.JButton();
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
